name: Code style

on:
  push:
    paths:
      - '**.php'
      - 'composer.json'
      - '.github/workflows/fix-php-code-style-issues.yml'
  pull_request:
    paths:
      - '**.php'
      - 'composer.json'
      - '.github/workflows/fix-php-code-style-issues.yml'

jobs:
  pint:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: none

      - name: Install dependencies
        uses: ramsey/composer-install@v4

      - name: Check code style
        run: ./vendor/bin/pint --test
